"""Zlib-specific DifferentialConfig — ready-to-plug into Stage 5.

Wires up the C FFI signatures and AlgorithmHarness configs that differentially
test generated zlib Rust against C zlib (via zlib1.dll / libz).

Phase D usage:

    from alchemist.verifier.differential_tester import verify_workspace
    from alchemist.verifier.zlib_config import zlib_diff_config

    report = verify_workspace(output_dir, diff_config=zlib_diff_config())
    assert report.passed  # only true if ALL 4 gates pass
"""

from __future__ import annotations

from pathlib import Path

from alchemist.verifier.auto_ffi import CSignature, TypedefMap
from alchemist.verifier.differential_tester import DifferentialConfig
from alchemist.verifier.proptest_gen import AlgorithmHarness


# ---------------------------------------------------------------------------
# C zlib FFI signatures
# ---------------------------------------------------------------------------

def zlib_public_signatures() -> list[CSignature]:
    """The subset of zlib's public API we exercise in Phase D."""
    return [
        CSignature(
            name="adler32",
            return_type="uLong",
            params=[
                ("adler", "uLong"),
                ("buf", "const Bytef *"),
                ("len", "uInt"),
            ],
        ),
        CSignature(
            name="crc32",
            return_type="uLong",
            params=[
                ("crc", "uLong"),
                ("buf", "const Bytef *"),
                ("len", "uInt"),
            ],
        ),
        CSignature(
            name="compress",
            return_type="int",
            params=[
                ("dest", "Bytef *"),
                ("destLen", "uLongf *"),
                ("source", "const Bytef *"),
                ("sourceLen", "uLong"),
            ],
        ),
        CSignature(
            name="uncompress",
            return_type="int",
            params=[
                ("dest", "Bytef *"),
                ("destLen", "uLongf *"),
                ("source", "const Bytef *"),
                ("sourceLen", "uLong"),
            ],
        ),
    ]


def zlib_typedefs() -> TypedefMap:
    """Zlib uses its own typedefs (uLong, Bytef, uInt). Map them to Rust."""
    # The auto_ffi C_SCALAR_MAP already knows uLong / Bytef / uInt. Returning an
    # empty TypedefMap keeps the default behavior.
    return TypedefMap()


# ---------------------------------------------------------------------------
# AlgorithmHarnesses — differential tests generated by proptest_gen
# ---------------------------------------------------------------------------

def zlib_harnesses() -> list[AlgorithmHarness]:
    """Per-algorithm differential harnesses for the zlib translation.

    The `rust_*` / `c_*` wrapper fns these call expressions reference are
    EMITTED by alchemist.verifier.adapter_gen into the synthesized diff_test
    crate's lib.rs: the c_* side wraps the FFI crate's raw externs, the
    rust_* side is resolved against the actual generated API by scanning the
    workspace sources. A harness that can't be resolved becomes a failing
    test — never a silent skip.
    """
    return [
        AlgorithmHarness(
            algorithm="adler32",
            category="checksum",
            rust_call="rust_adler32(&input)",
            c_call="c_adler32(&input)",
            seed=1,  # RFC 1950: Adler-32 starts at 1
            cases=5000,
        ),
        AlgorithmHarness(
            algorithm="crc32",
            category="checksum",
            rust_call="rust_crc32(&input)",
            c_call="c_crc32(&input)",
            seed=0,  # RFC 1952: CRC-32 starts at 0
            cases=5000,
        ),
        AlgorithmHarness(
            algorithm="deflate",
            category="compression",
            rust_call="rust_compress(&input)",
            c_call="c_compress(&input)",
            rust_decompress_call="rust_uncompress(&compressed, input.len() + 64)",
            c_decompress_call="c_uncompress(&compressed, input.len() + 64)",
            cases=1000,
        ),
    ]


# ---------------------------------------------------------------------------
# Top-level builder
# ---------------------------------------------------------------------------

def zlib_diff_config(
    c_source_dir: Path,
    *,
    include_dirs: list[Path] | None = None,
) -> DifferentialConfig:
    """Build a DifferentialConfig tailored to zlib.

    Args:
        c_source_dir: directory containing zlib's C source (*.c + *.h).
        include_dirs: additional include paths for the C DLL build.
    """
    c_sources = sorted(
        f for f in Path(c_source_dir).glob("*.c")
        if "test" not in f.name.lower()
        and "example" not in f.name.lower()
    )
    return DifferentialConfig(
        c_sources=c_sources,
        c_include_dirs=list(include_dirs or [Path(c_source_dir)]),
        c_public_signatures=zlib_public_signatures(),
        c_typedefs=zlib_typedefs(),
        c_opaque_types=set(),
        harnesses=zlib_harnesses(),
        ffi_crate_name="c_zlib_ref",
    )


def zlib_checksum_diff_config(
    c_source_dir: Path,
    *,
    include_dirs: list[Path] | None = None,
) -> DifferentialConfig:
    """Checksum-crate-scoped DifferentialConfig.

    Runs the compile/anti-stub/test gates against the zlib-checksum package
    only, with the adler32 + crc32 differential harnesses. Use this to verify
    the checksum crate while the compression/inflate crates are still
    skeletons — their gates stay red under the full config, which is correct,
    but shouldn't mask a genuinely verifiable checksum crate.
    """
    cfg = zlib_diff_config(c_source_dir, include_dirs=include_dirs)
    cfg.harnesses = [h for h in cfg.harnesses if h.category == "checksum"]
    cfg.packages = ["zlib-checksum"]
    return cfg
